# -*- mode:org;coding:utf-8 -*-

#+AUTHOR: Pascal J. Bourguignon
#+EMAIL: pjb@informatimago.com
#+DATE: Thu Oct 22 10:24:42 CEST 2020
#+TITLE: Notes de version de l'application Patchwork
#+LANGUAGE: fr

* Prologue                                                         :noexport:

#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage[english]{babel}
#+LATEX_HEADER: \pagestyle{fancyplain}
#+LATEX_HEADER: \lhead{\small{}}
#+LATEX_HEADER: \chead{}
#+LATEX_HEADER: \rhead{Release Notes for the Patchwork application}
#+LATEX_HEADER: \lfoot{}
#+LATEX_HEADER: \cfoot{\tiny{Copyright 2020, Pascal J. Bourguignon}}
#+LATEX_HEADER: \rfoot{\thepage}
#+LATEX_HEADER: \setcounter{page}{1}
#+LATEX_HEADER: \pagenumbering{arabic}

* NOTES DE VERSION DE L'APPLICATION PATCHWORK

Les nouvelles version de l'application Patchwork sont entreprosées à
l'adresse :

ftp://ftp.informatimago.com/users/pjb/patchwork/

** Prochaines versions

Principaux problèmes restant dans la version en cours :

- le dessin des instances et le dessin des lignes ne marchent pas (déplacement des boîtes,
  changement de taille).
  https://framagit.org/patchwork/patchwork/-/issues/14

La liste complète des problèmes restant se trouve à l'adresse :

https://framagit.org/patchwork/patchwork/-/issues

** 10.1-0.545

- Correction du problème de chargement et d'enregistrement des fichiers MIDI.
  Vérifier midi-save, il devrait enregistrer en séquence dans le fichier MIDI tous les
  objets dans ses entrées au lieu d'un seul.
  https://framagit.org/patchwork/patchwork/-/issues/13

- Correction d'une bogue qui bloquait ou ralentissait une sortie plus importante dans l'auditeur.
  Désormais, il devrait afficher rapidement même les grosses sorties.
  https://framagit.org/patchwork/patchwork/-/issues/15

- En plus de ~*value*~, il y a une variable ~*values*~ qui contient une
  liste des valeurs renvoyées par la dernière évaluation du patch.

** 10.1-0.722

- Mis à jour pour fonctionner sur macOS Sierra.

- Les fichiers Lisp de =~/Documents/Patchwork/PW-inits/= sont chargés lorsque le
  l'application est lancée, pour l'initialisation de l'utilisateur.  Un exemple
  Le fichier ~init.lisp~ est fourni; déplacez-le dans
  =~/Documents/Patchwork/PW-inits/=.  Il définit un alias PW pour
  ~pw:*valeur*~ et deux fonctions de raccourci ~(patchwork)~ et ~(lisp)~ pour
  basculer entre l'application patchwork et l'environnement lisp.

- Mise en œuvre de la case à cocher et du dessin par bouton radio, alors maintenant ils s'affichent.
  Pas encore implémenté: hilitation des contrôles pendant le déplacement de la souris et suivi.

- Utilisation de la police Maestro.
  Problèmes:

     + la police ~Maestro.ttf~ mappe les caractères Maestro en unicode #xf021 - #xf0f0;
       nous compensons le code de caractère lors de l'utilisation de
       cette police, mais il semble que certains caractères ont des
       décalages de code différents (par exemple, dièze), donc
       actuellement ils s'affichent pas (le caractère de remplacement
       est affiché).

     + les métriques sont différentes, donc les caractères ne sont pas affichés
       là où prévu, par exemple, les lignes de partition  ne sont pas
       correctement positionnées; les les notes semblent être placées
       plus haut (il faut cliquer en dessous pour sélectionnez-les ou
       déplacez-les).

   Actuellement, la police Maestro doit être installée dans le répertoire système ~/Library/Fonts~.
   Finalement, il sera utilisé sans installation, directement à partir des ressources de l'application.

- la variable ~PW:*VALUE*~ est liée à la dernière valeur évaluée
  (imprimée après «=PW->=»).   Il peut ensuite être utilisé dans le REPL:
#+BEGIN_SRC
        CL-USER ? (in-package :pw)
        #<Package "PATCHWORK">
        PW ? PW->#<C-CHORD #x302005B97FAD>
        *value*
        #<C-CHORD #x302005ABE27D>
        PW ? (notes *value*)
        (#<C-NOTE #x302005ABE64D> #<C-NOTE #x302005ABE59D>
         #<C-NOTE #x302005ABE4ED> #<C-NOTE #x302005ABE43D>
         #<C-NOTE #x302005ABE38D> #<C-NOTE #x302005ABE2DD>)
        PW ? (ask-all (notes *value*) 'midic)
        (2000 2400 2700 3800 6000 8700)
        PW ?
#+END_SRC

- La redirection vers la fenêtre Listener est corrigée.

- Amélioration de la vitesse de chargement des documents de patch en supprimant les journaux de débogage.
  (~&2Ryt~ se charge en moins de 10 secondes sur iMac 4 GHz Intel Core i7).

** 10.0-0.607

- Corrected multi-bpf and bpf-lib crashes.
- Implemented pop-up menus.
- Made use of the Maestro font instead of Mus-Not-j, corrected chord-box displaying.
- Added (interlock subs-posn group-list first-n last-n) to Kernel/List menu.
- Corrected origin of line when click-and-dragging from the output box.
- Implemented TextEdit, editable-text-dialog-item.
  Still need some graphic adjustments, and some integration debugging.

** 10.0-0.714

- Corrected the PW-USER logical host translations loading.  See PW-USER
  in note 10.0-0.737 below.

** 10.0-0.717

- Optimized a little loading and display time.
- Added .pwpatch or .midi extensions to saved file names.
- Corrected double window close bug (asked twice whether to save a modified patch window on close).
- Corrected a few internal bugs (all make-array should have a :initial-element, etc).

** 10.0-0.737

This release let you load an generate MIDI files, using the Common
Lisp MIDI library (from Robert Strandh at Bordeaux), instead of
MidiShare, which is not entirely ported to MacOSX 64-bit yet.

This release uses the new graphic model where MCL view classes don't
have a matching Cocoa NSView class.

The text fields, controls and dialogs are not completed yet.


- PW-USER configured by default as =~/Documents/Patchwork/=
  This can be changed by adding or editing the file =~/LOGHOSTS/PW-USER=
  with a sexp such as:
#+BEGIN_SRC
      #.(let ((pw-user (merge-pathnames #P"Documents/Patchwork/" (user-homedir-pathname))))
          `(("**;*.*.*" ,(merge-pathnames "**/*.*" pw-user))
            ("**;*.*"   ,(merge-pathnames "**/*.*" pw-user))
            ("**;*"     ,(merge-pathnames "**/*"   pw-user))))
#+END_SRC
   The PW-USER directory contains the following directories and files:
#+BEGIN_SRC
        abstract-autoload/
        library-autoload/
        PW-inits/
        PW-inits/init.lisp
        PW-inits/config.init
        PW-user-library/
        PW-user-patches/
#+END_SRC

- when an error occurs in a listener window, the debugger is invoked
  in the same listener window, instead of closing the listener window.
- corrected the menu titles: Patchwork, Apps, … instead of Clozure CL, Patchwork, …
- set the icon of the application.
- Added “Show Scheduler Queue” menu item.
- Replaced Midishare by CL-MIDI.
- implemented show-documentation and partially edit-definition.

** 10.0-0.907

- adding links works.
- drawing of outboxes works.
- dragging the top bar of a patch moves it.
- moving a box works also after the first time.
- resizing a box works also after the first time.
- patchwork-trace.txt is written in the user's Desktop instead of pjb's.

** 10.0-0.922, 10.0-0.919

- Set the minimum system version to 10.3 when compiled on 10.5 and 10.6 otherwise.
- Backported to ccl-1.6 on MacOSX 10.5.8
- Implemented redirection to listener windows.
- Corrected switching between lisp and patchwork menubar.
- Corrected moving and resizing of patch boxes.
- Corrected selection of patches by click-and-drag of a grow rect arround them.
- Added instance drawing to replace srcXor trick.

* Epilogue                                                         :noexport:
# THE END

# Local Variables:
# eval: (auto-fill-mode 1)
# eval: (set-input-method 'latin-1-prefix)
# End:
