# -*- mode:org;coding:utf-8 -*-

#+AUTHOR: Pascal J. Bourguignon
#+EMAIL: pjb@informatimago.com
#+DATE: Thu Oct 22 10:24:42 CEST 2020
#+TITLE: Release Notes for the Patchwork application
#+LANGUAGE: en

* Prologue                                                         :noexport:

#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage[english]{babel}
#+LATEX_HEADER: \pagestyle{fancyplain}
#+LATEX_HEADER: \lhead{\small{}}
#+LATEX_HEADER: \chead{}
#+LATEX_HEADER: \rhead{Release Notes for the Patchwork application}
#+LATEX_HEADER: \lfoot{}
#+LATEX_HEADER: \cfoot{\tiny{Copyright 2020, Pascal J. Bourguignon}}
#+LATEX_HEADER: \rfoot{\thepage}
#+LATEX_HEADER: \setcounter{page}{1}
#+LATEX_HEADER: \pagenumbering{arabic}

* PATCHWORK RELEASE NOTES

Patchwork applications releases are stored in:

ftp://ftp.informatimago.com/users/pjb/patchwork/

** next release


Issues remaining in current release:

- instance drawing doesn't occur (threads?) (moving, growing boxes).
- also: lines don't draw (threads?)

The full list can be found at:

https://framagit.org/patchwork/patchwork/-/issues

** 10.1-0.547

- Corrected the problem with loading and saving MIDI files.
  Check midi-save, it should save in sequence in the MIDI file all the
  objects in its inputs instead of just one.
  https://framagit.org/patchwork/patchwork/-/issues/13

- Corrected bug that blocked or slowed bigger output in the listener.
  Now, it should display quickly even big outputs.
  https://framagit.org/patchwork/patchwork/-/issues/15

- In addition to ~*value*~, there's a ~*values*~ variable that holds a
  list of values returned by the last patch evaluation.

** 10.1-0.722

- Updated to work on macOS Sierra.

- Lisp files from =~/Documents/Patchwork/PW-inits/= are loaded when the
  application is launched, for user initialization.  An example
  ~init.lisp~ file is provided; move it to
  =~/Documents/Patchwork/PW-inits/=.  It defines an alias PW for
  ~pw:*value*~ and two shortcut functions ~(patchwork)~ and ~(lisp)~ to
  switch between the patchwork application and the lisp environment.

- Implemented check-box and radio-button drawing, so now they show.
  Not implemented yet: hiliting the controls during the mouse down and tracking.

- Made use of the Maestro font.
  Problems:

     + the ~Maestro.ttf~ font maps Maestro characters to unicode #xf021 - #xf0f0;
       we offset the character code when using this font, however it looks like
       some characters have different code offsets (eg. flat), so currently they
       don't show (placeholder character is displayed).

     + the metrics are different, so the characters are not displayed
       where expected, eg. the staff is not positionned properly; the
       notes seems to be placed higher (we must click below them to
       select or move them).

   Currently the Maestro font needs to be installed in the system ~/Library/Fonts~ directory.
   Eventually it'll be used with no installation, directly from the application resources.

- the variable ~PW:*VALUE*~ is bound to the last value evaluated (printed after “=PW->=”).
  It can then be used in the REPL:

#+BEGIN_SRC
        CL-USER ? (in-package :pw)
        #<Package "PATCHWORK">
        PW ? PW->#<C-CHORD #x302005B97FAD>
        *value*
        #<C-CHORD #x302005ABE27D>
        PW ? (notes *value*)
        (#<C-NOTE #x302005ABE64D> #<C-NOTE #x302005ABE59D>
         #<C-NOTE #x302005ABE4ED> #<C-NOTE #x302005ABE43D>
         #<C-NOTE #x302005ABE38D> #<C-NOTE #x302005ABE2DD>)
        PW ? (ask-all (notes *value*) 'midic)
        (2000 2400 2700 3800 6000 8700)
        PW ?
#+END_SRC

- Redirection to the Listener window is corrected.

- Improved speed of loading patch documents by removing debugging logs.
  (~&2Ryt~ loads in less than 10 seconds on iMac 4 GHz Intel Core i7).

** 10.0-0.607

- Corrected multi-bpf and bpf-lib crashes.
- Implemented pop-up menus.
- Made use of the Maestro font instead of Mus-Not-j, corrected chord-box displaying.
- Added (interlock subs-posn group-list first-n last-n) to Kernel/List menu.
- Corrected origin of line when click-and-dragging from the output box.
- Implemented TextEdit, editable-text-dialog-item.
  Still need some graphic adjustments, and some integration debugging.

** 10.0-0.714

- Corrected the PW-USER logical host translations loading.  See PW-USER
  in note 10.0-0.737 below.

** 10.0-0.717

- Optimized a little loading and display time.
- Added .pwpatch or .midi extensions to saved file names.
- Corrected double window close bug (asked twice whether to save a modified patch window on close).
- Corrected a few internal bugs (all make-array should have a :initial-element, etc).

** 10.0-0.737

This release let you load an generate MIDI files, using the Common
Lisp MIDI library (from Robert Strandh at Bordeaux), instead of
MidiShare, which is not entirely ported to MacOSX 64-bit yet.

This release uses the new graphic model where MCL view classes don't
have a matching Cocoa NSView class.

The text fields, controls and dialogs are not completed yet.


- PW-USER configured by default as =~/Documents/Patchwork/=
  This can be changed by adding or editing the file =~/LOGHOSTS/PW-USER=
  with a sexp such as:
#+BEGIN_SRC
      #.(let ((pw-user (merge-pathnames #P"Documents/Patchwork/" (user-homedir-pathname))))
          `(("**;*.*.*" ,(merge-pathnames "**/*.*" pw-user))
            ("**;*.*"   ,(merge-pathnames "**/*.*" pw-user))
            ("**;*"     ,(merge-pathnames "**/*"   pw-user))))
#+END_SRC
   The PW-USER directory contains the following directories and files:
#+BEGIN_SRC
        abstract-autoload/
        library-autoload/
        PW-inits/
        PW-inits/init.lisp
        PW-inits/config.init
        PW-user-library/
        PW-user-patches/
#+END_SRC

- when an error occurs in a listener window, the debugger is invoked
  in the same listener window, instead of closing the listener window.
- corrected the menu titles: Patchwork, Apps, … instead of Clozure CL, Patchwork, …
- set the icon of the application.
- Added “Show Scheduler Queue” menu item.
- Replaced Midishare by CL-MIDI.
- implemented show-documentation and partially edit-definition.

** 10.0-0.907

- adding links works.
- drawing of outboxes works.
- dragging the top bar of a patch moves it.
- moving a box works also after the first time.
- resizing a box works also after the first time.
- patchwork-trace.txt is written in the user's Desktop instead of pjb's.

** 10.0-0.922, 10.0-0.919

- Set the minimum system version to 10.3 when compiled on 10.5 and 10.6 otherwise.
- Backported to ccl-1.6 on MacOSX 10.5.8
- Implemented redirection to listener windows.
- Corrected switching between lisp and patchwork menubar.
- Corrected moving and resizing of patch boxes.
- Corrected selection of patches by click-and-drag of a grow rect arround them.
- Added instance drawing to replace srcXor trick.

* Epilogue                                                         :noexport:
# THE END

# Local Variables:
# eval: (auto-fill-mode 1)
# eval: (set-input-method 'latin-1-prefix)
# End:
